name: Issue and PR labels

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request:
    types: [opened, reopened]

jobs:
  applyNeedsAttentionLabel:
    name: Apply Needs Attention Label
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Apply Needs Attention Label
        uses: hramos/needs-attention@v2.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          response-required-label: "waiting-for-response"
          needs-attention-label: "needs-triage"

  applyPRLabel:
    name: Apply Needs Attention for PRs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Label PRs for Triage
        uses: hramos/needs-attention@v2.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          response-required-label: "waiting-for-author-feedback"
          needs-attention-label: "needs-team-review"
