name: Check PRs for Review Inactivity

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour to check for inactivity.
  pull_request_target:
    types: [labeled, unlabeled] # Triggers when labels are modified on PRs.
  workflow_dispatch:

jobs:
  check-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set current day of the week
        run: echo "DAY_OF_WEEK=$(date +'%u')" >> $GITHUB_ENV

      - name: Check for needs-review label and inactivity
        id: check_needs_review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if it's a working day (1 = Monday, 5 = Friday)
          if [[ "$DAY_OF_WEEK" -ge 6 ]]; then
            echo "Not a working day. Skipping notification."
            exit 0
          fi

          # Get list of pull requests with the `needs-team-review` label
          eight_hours=8*3600 # 8 hours in seconds
          five_minutes=5*60 # 5 minutes in seconds
          inactivity_threshold=five_minutes
          prs=$(gh pr list --label "needs-team-review" --json number,title,updatedAt,reviewRequests --jq '.[] | select(.updatedAt < (now - inactivity_threshold) | todateiso8601)')

          if [[ -z "$prs" ]]; then
            echo "No PRs need action."
            exit 0
          fi

          echo "pr_list=${prs}" >> $GITHUB_ENV

  notify-slack:
    runs-on: ubuntu-latest
    needs: check-prs
    if: steps.check_needs_review.outputs.pr_list
    steps:
      - name: Notify Inactive PRs on Slack
        uses: "ravsamhq/notify-slack-action@2.5.0"
        with:
          status: failure
          notification_title: "PRs Pending Review"
          message_format: |
            *PR #${{ steps.check_needs_review.outputs.pr_number }} - ${{ steps.check_needs_review.outputs.pr_title }}* needs review.
            <% if reviewers -%>
              Reviewers: *${{ steps.check_needs_review.outputs.reviewers }}*
            <% else -%>
              No reviewers assigned. Notifying channel.
            <% end %>
          footer: "Linked Repo <${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}> | <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View trigger>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
