name: Label Issues and PRs on Open/Reopen

on:
  issues:
    types: [opened, reopened] # Trigger when an issue is opened or reopened
  pull_request:
    types: [opened, reopened] # Trigger when a PR is opened or reopened

jobs:
  labelIssuePR:
    name: Apply Label to Issues and PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add Label to Issue or PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Check if it's an issue or a PR
            if (context.eventName === 'issues') {
              // Add label to issue
              await github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                labels: ['needs-team-review']
              });
            } else if (context.eventName === 'pull_request') {
              // Add label to PR
              await github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: ['needs-team-review']
              });
            }
          result-encoding: string
        id: result
      - name: Get result
        run: echo "${{steps.result.outputs.result}}"
